services:
  backend:
    build: ./Backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/tours
      - REDIS_URL=mongodb://mongo:27017/tours
      - REDIS_HOST=redis
      - REDIS_PORT=12264
      - REDIS_PASSWORD=niLrzCcf7F72YyAcfQpbLrRBavFieUPE
    depends_on:
      - mongo
      - redis
    restart: always

  frontend:
    build: ./Frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass your_redis_password

volumes:
  mongo-data:
  redis_data: