services:
  backend:
    build: ./Backend
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb+srv://rohithyadavm22:SHqXRdzu13o7BkQP@cluster0.knztryo.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - REDIS_HOST=redis-12264.c276.us-east-1-2.ec2.redns.redis-cloud.com
      - REDIS_PORT=12264
      - REDIS_USERNAME=default
      - REDIS_PASSWORD=niLrzCcf7F72YyAcfQpbLrRBavFieUPE
    depends_on:
      - mongo
      - redis
    restart: always

  frontend:
    build: ./Frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass your_redis_password

volumes:
  mongo-data:
  redis_data: