name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest  # Explicitly specify Linux runner

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Dependencies
      run: |
        cd Frontend
        npm install
        cd ../Backend
        npm install

    - name: Run Tests
      run: |
        cd Frontend
        npm test
        cd ../Backend
        npm test

    - name: Build and Test Docker Images
      run: |
        docker build -f Frontend/Dockerfile -t test-frontend ./Frontend
        docker build -f Backend/Dockerfile -t test-backend ./Backend